/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computacionfim.conversorhorarios;


import java.awt.FileDialog;
import java.awt.Image;
import java.awt.*;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author oscar
 */
public class InterfazConversor extends javax.swing.JFrame {
    Thread t;
    Thread t2;
    String pathNew;
    String nameNew;
    String pathFile;
    String nameFile;
    File mainFile;
    Icon load;
    Icon ok;
    Icon bug;
    Icon add;
    Icon gif;

    /**
     * Creates new form InterfazConversor
     */
    public InterfazConversor() {
        initComponents();
        
        ImageIcon img = new ImageIcon(InterfazConversor.class.getClassLoader().getResource("fileLoadHD.png"));
        load = new ImageIcon(img.getImage().getScaledInstance(imgLBL.getWidth(), imgLBL.getHeight(), Image.SCALE_SMOOTH));
        img = new ImageIcon(InterfazConversor.class.getClassLoader().getResource("fileBugHD.png"));
        bug = new ImageIcon(img.getImage().getScaledInstance(imgLBL.getWidth(), imgLBL.getHeight(), Image.SCALE_SMOOTH));
        img = new ImageIcon(InterfazConversor.class.getClassLoader().getResource("fileOkHD.png"));
        ok = new ImageIcon(img.getImage().getScaledInstance(imgLBL.getWidth(), imgLBL.getHeight(), Image.SCALE_SMOOTH));
        img = new ImageIcon(InterfazConversor.class.getClassLoader().getResource("fileAddHD.png"));
        add = new ImageIcon(img.getImage().getScaledInstance(imgLBL.getWidth(), imgLBL.getHeight(), Image.SCALE_SMOOTH));
        img = new ImageIcon(InterfazConversor.class.getClassLoader().getResource("ring.gif"));
        gif = new ImageIcon(img.getImage().getScaledInstance(imgLBL.getWidth(), imgLBL.getHeight(), Image.SCALE_DEFAULT));
        imgLBL.setIcon(add);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Control_CC = new computacionfim.conversorhorarios.ControlConversor();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        directorio_LBL = new javax.swing.JLabel();
        archivo_LBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        selector_BTN = new javax.swing.JButton();
        imgLBL = new javax.swing.JLabel();
        estado_LBL = new javax.swing.JLabel();
        convertir_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        archivo_LBL2 = new javax.swing.JLabel();
        directorio_LBL2 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Archivo Original:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversion de archivos de Horarios");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(500, 300));

        jPanel1.setBackground(new java.awt.Color(84, 156, 73));

        directorio_LBL.setBackground(new java.awt.Color(255, 255, 255));
        directorio_LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        directorio_LBL.setForeground(new java.awt.Color(255, 255, 255));
        directorio_LBL.setText("X:\\");
            directorio_LBL.setInheritsPopupMenu(false);

            archivo_LBL.setBackground(new java.awt.Color(255, 255, 255));
            archivo_LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            archivo_LBL.setForeground(new java.awt.Color(255, 255, 255));
            archivo_LBL.setText(">");

            jPanel2.setBackground(new java.awt.Color(255, 255, 255));

            selector_BTN.setBackground(new java.awt.Color(84, 156, 73));
            selector_BTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            selector_BTN.setForeground(new java.awt.Color(255, 255, 255));
            selector_BTN.setText("Subir Archivo");
            selector_BTN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    selector_BTNActionPerformed(evt);
                }
            });

            imgLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            estado_LBL.setBackground(new java.awt.Color(51, 51, 51));
            estado_LBL.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
            estado_LBL.setForeground(new java.awt.Color(51, 51, 51));
            estado_LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(estado_LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(selector_BTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(32, 32, 32))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(imgLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                    .addComponent(estado_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(selector_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30))
            );

            convertir_BTN.setBackground(new java.awt.Color(255, 51, 51));
            convertir_BTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
            convertir_BTN.setForeground(new java.awt.Color(255, 255, 255));
            convertir_BTN.setText("Convertir Arhivo");
            convertir_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    convertir_BTNMouseClicked(evt);
                }
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    convertir_BTNMousePressed(evt);
                }
            });
            convertir_BTN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    convertir_BTNActionPerformed(evt);
                }
            });

            jLabel1.setBackground(new java.awt.Color(51, 51, 51));
            jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(51, 51, 51));
            jLabel1.setText("Archivo Nuevo:");

            jLabel2.setBackground(new java.awt.Color(51, 51, 51));
            jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(51, 51, 51));
            jLabel2.setText("Archivo Original:");

            archivo_LBL2.setBackground(new java.awt.Color(255, 255, 255));
            archivo_LBL2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            archivo_LBL2.setForeground(new java.awt.Color(255, 255, 255));
            archivo_LBL2.setText(">");

            directorio_LBL2.setBackground(new java.awt.Color(255, 255, 255));
            directorio_LBL2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            directorio_LBL2.setForeground(new java.awt.Color(255, 255, 255));
            directorio_LBL2.setText("X:\\");
                directorio_LBL2.setInheritsPopupMenu(false);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(convertir_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(directorio_LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(archivo_LBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(directorio_LBL2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(archivo_LBL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(archivo_LBL)
                        .addGap(18, 18, 18)
                        .addComponent(directorio_LBL)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(archivo_LBL2)
                        .addGap(18, 18, 18)
                        .addComponent(directorio_LBL2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(convertir_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void convertir_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertir_BTNActionPerformed
       t = new Thread(new Runnable() {
            @Override
            public void run() {
                estado_LBL.setText("Trabajando");
                imgLBL.setIcon(gif);
            }
        });
       t2= new Thread(new Runnable() {
            @Override
            public void run() {
                boolean validFile = Control_CC.leerXLS(mainFile);
                if (!validFile) {
                    archivo_LBL.setText(String.format("<html><div WIDTH=%d>%s</div></html>", archivo_LBL.getWidth(), nameFile+" >FORMATO NO VALIDO<"));
                    imgLBL.setIcon(bug);
                    t.interrupt();
                    estado_LBL.setText("Error");
                } else {
                    nameNew=Control_CC.getNameNew();
                    pathNew=Control_CC.getPathNew();
                    archivo_LBL2.setText(String.format("<html><div WIDTH=%d>%s</div></html>", archivo_LBL2.getWidth(), nameNew));
                    directorio_LBL2.setText(String.format("<html><div WIDTH=%d>%s</div></html>", directorio_LBL2.getWidth(), pathNew));
                    imgLBL.setIcon(ok);
                    t.interrupt();
                    estado_LBL.setText("Realizado");
                }
                t2.interrupt();   
            }
        });
       t.start();
       t2.start();        
    }//GEN-LAST:event_convertir_BTNActionPerformed

    private void convertir_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertir_BTNMouseClicked

    }//GEN-LAST:event_convertir_BTNMouseClicked

    private void convertir_BTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertir_BTNMousePressed

    }//GEN-LAST:event_convertir_BTNMousePressed

    private void selector_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selector_BTNActionPerformed
        estado_LBL.setText("Sin Archivo");
        FileDialog FD = new java.awt.FileDialog(this, "Selecciona Archivo", FileDialog.LOAD);
        FD.setVisible(true);
        String selFile = FD.getFile();
        if (selFile != null) {
            estado_LBL.setText("Archivo Cargado");
            pathFile = FD.getDirectory() + selFile;
            mainFile = new File(pathFile);
            nameFile = FD.getFile();
            archivo_LBL.setText(String.format("<html><div WIDTH=%d>%s</div></html>", archivo_LBL.getWidth(), nameFile));
            directorio_LBL.setText(String.format("<html><div WIDTH=%d>%s</div></html>", directorio_LBL.getWidth(), pathFile));
            imgLBL.setIcon(load);
            archivo_LBL2.setText(">");
            directorio_LBL2.setText("X:\\");
        }
    }//GEN-LAST:event_selector_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private computacionfim.conversorhorarios.ControlConversor Control_CC;
    private javax.swing.JLabel archivo_LBL;
    private javax.swing.JLabel archivo_LBL2;
    private javax.swing.JButton convertir_BTN;
    private javax.swing.JLabel directorio_LBL;
    private javax.swing.JLabel directorio_LBL2;
    private javax.swing.JLabel estado_LBL;
    private javax.swing.JLabel imgLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton selector_BTN;
    // End of variables declaration//GEN-END:variables
}
